name: build pdf
on:
  push:
    tags:
    - 'v*'
 
permissions:
  contents: write
  
jobs:
  build-pdf:
    name: build pdf
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Install Bundler
      run: gem install bundler

    - name: Install Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install Font
      run: |
        curl -O https://moji.or.jp/wp-content/ipafont/IPAexfont/IPAexfont00401.zip
        unzip -o IPAexfont00401.zip
        mv IPAexfont00401/* fonts/
        rm -rf IPAexfont00401
        rm -f IPAexfont00401.zip

    - name: Generate PDF
      # ここのコマンド外部ファイルから読み込みたい
      run: ruby make_cv.rb -s style.txt -o output.pdf
      
    - name: Upload PDF to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: output.pdf
